# Generated by Django 5.1.1 on 2026-06-16 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0011_remove_deliverydriver_license_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_gross",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount before any deductions.",
                        max_digits=10,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Amount deducted for taxes.",
                        max_digits=10,
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Platform commission deducted from gross amount.",
                        max_digits=10,
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Net amount paid to the driver (gross - tax - commission).",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Processing", "Processing"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                            ("Canceled", "Canceled"),
                        ],
                        default="Pending",
                        help_text="Current status of the payout.",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_transfer_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the corresponding Stripe transfer, if applicable.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True,
                        help_text="Start date of the earning period for this payout.",
                        null=True,
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True,
                        help_text="End date of the earning period for this payout.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the payout was processed.",
                        null=True,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        help_text="The driver receiving the payout.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="users.deliverydriver",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payout",
                "verbose_name_plural": "Payouts",
                "ordering": ["-created_at"],
            },
        ),
    ]
