# Generated by Django 5.1.1 on 2026-06-25 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        ("users", "0017_deliverer_onboardtoken_payrollstats_salaryrecord_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payout",
            name="driver",
            field=models.ForeignKey(
                help_text="The driver receiving the payout.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payouts",
                to="users.deliverer",
            ),
        ),
    ]
