# Generated by Django 4.2.14 on 2026-08-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payout_driver"),
    ]

    operations = [
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Salary amount.", max_digits=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Paid", "Paid")],
                        default="Pending",
                        help_text="Current status of the salary.",
                        max_length=20,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True,
                        help_text="Start date of the earning period for this salary.",
                        null=True,
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True,
                        help_text="End date of the earning period for this salary.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the salary was paid.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Salary",
                "verbose_name_plural": "Salaries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Payout",
        ),
    ]
