# Generated by Django 4.2.14 on 2026-08-13 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_salary_delete_payout"),
        ("users", "0024_deliverydriver_remove_deliverer_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="driver",
            field=models.ForeignKey(
                help_text="The driver receiving the salary.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salaries",
                to="users.deliverydriver",
            ),
        ),
    ]
