# Generated by Django 5.2.14 on 2026-05-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cart',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='auth_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
