# Generated by Django 5.2.14 on 2026-05-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_telegrambotuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegrambotuser",
            name="last_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
