# Generated by Django 5.2.14 on 2026-05-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_telegrambotuser_last_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegrambotuser",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
    ]
