# Generated by Django 5.2.14 on 2026-05-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_telegrambotuser_is_banned"),
    ]

    operations = [
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("is_busy", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
