# Generated by Django 5.2.14 on 2026-05-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_operator"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bad_comments_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
    ]
