# Generated by Django 5.1.1 on 2026-06-14 06:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_customuser_avatar_alter_seller_avatar_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryDriver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Driver phone number in international format",
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?\\d{7,15}$", message="Enter a valid phone number."
                            )
                        ],
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("bike", "Bicycle"),
                            ("motorbike", "Motorbike"),
                            ("car", "Car"),
                            ("van", "Van"),
                            ("other", "Other"),
                        ],
                        default="motorbike",
                        help_text="Type of vehicle used by the driver",
                        max_length=20,
                    ),
                ),
                (
                    "vehicle_description",
                    models.CharField(
                        blank=True,
                        help_text="Optional vehicle description (brand, color, plate)",
                        max_length=128,
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True,
                        help_text="Driver license or registration number (optional)",
                        max_length=64,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the driver is currently active and can receive assignments",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the driver is currently available for new deliveries",
                    ),
                ),
                (
                    "current_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Current latitude",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "current_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Current longitude",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "last_location_update",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last location update",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Linked user account for the driver",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_driver_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery Driver",
                "verbose_name_plural": "Delivery Drivers",
                "ordering": ["-is_available", "user__id"],
            },
        ),
    ]
