# Generated by Django 5.1.1 on 2026-06-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_deliverydriver_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydriver',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='Stripe Connect Account ID for payouts', max_length=255, null=True),
        ),
    ]
