# Generated by Django 5.1.1 on 2026-06-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_customuser_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                default="admin@example.com", max_length=254, unique=True
            ),
        ),
    ]
