# Generated by Django 5.1.1 on 2026-06-25 15:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_alter_customuser_managers_adminloginattempt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deliverer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+998901234567'. Up to 32 digits allowed.",
                                regex="^\\+?\\d{7,32}$",
                            )
                        ],
                    ),
                ),
                (
                    "vehicle_info",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Onboarding"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_account_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payout_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "rate_per_hour",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OnboardToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PayrollStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.PositiveSmallIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                ("total_gross", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_net", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_fees", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_payouts", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Payroll Stats",
            },
        ),
        migrations.CreateModel(
            name="SalaryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("hours_worked", models.DecimalField(decimal_places=2, max_digits=6)),
                ("rate_per_hour", models.DecimalField(decimal_places=2, max_digits=6)),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "taxes_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_payment_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-period_end", "deliverer__user__full_name"],
            },
        ),
        migrations.RemoveField(
            model_name="deliverydriver",
            name="user",
        ),
        migrations.RemoveIndex(
            model_name="adminloginattempt",
            name="users_admin_fingerp_3e3242_idx",
        ),
        migrations.RemoveField(
            model_name="adminloginattempt",
            name="attempts",
        ),
        migrations.RemoveField(
            model_name="adminloginattempt",
            name="blocked_until",
        ),
        migrations.RemoveField(
            model_name="adminloginattempt",
            name="fingerprint",
        ),
        migrations.RemoveField(
            model_name="adminloginattempt",
            name="ip",
        ),
        migrations.RemoveField(
            model_name="adminloginattempt",
            name="last_attempt",
        ),
        migrations.RemoveField(
            model_name="adminlogintoken",
            name="token",
        ),
        migrations.AddField(
            model_name="adminloginattempt",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="adminloginattempt",
            name="ip_address",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name="adminloginattempt",
            name="reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="adminloginattempt",
            name="success",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="adminloginattempt",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_login_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="adminlogintoken",
            name="token_hash",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("deliverer", "Deliverer"),
                    ("admin", "Admin"),
                    ("seller", "Seller"),
                ],
                default="customer",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="adminlogintoken",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="adminlogintoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="onboard_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deliverer",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliverer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="onboardtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payrollstats",
            unique_together={("month", "year")},
        ),
        migrations.AddField(
            model_name="salaryrecord",
            name="deliverer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary_records",
                to="users.deliverer",
            ),
        ),
    ]
