# Generated by Django 5.1.1 on 2026-06-25 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_order_driver_alter_orderdelivery_driver"),
        ("payments", "0002_alter_payout_driver"),
        ("users", "0017_deliverer_onboardtoken_payrollstats_salaryrecord_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeliveryDriver",
        ),
        migrations.AlterUniqueTogether(
            name="salaryrecord",
            unique_together={("deliverer", "period_start", "period_end")},
        ),
    ]
