# Generated by Django 5.1.1 on 2026-07-14 09:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_alter_customuser_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboardtoken",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="onboardtoken",
            name="token_hash",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="onboardtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="onboard_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
