# Generated by Django 5.1.1 on 2026-07-19 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_onboardtoken_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlogintoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_login_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
