# Generated by Django 5.1.1 on 2026-08-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_alter_adminlogintoken_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverer",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="deliverer_avatars/"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("admin", "Admin"),
                    ("seller", "Seller"),
                ],
                default="customer",
                max_length=10,
            ),
        ),
    ]
