# Generated by Django 4.2.14 on 2026-08-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_deliverer_avatar_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin"), ("seller", "Seller")],
                default="user",
                max_length=10,
            ),
        ),
    ]
