# Generated by Django 4.2.14 on 2026-08-13 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_salary_delete_payout"),
        ("users", "0023_alter_customuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryDriver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "vehicle_info",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=50,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="drivers/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="deliverer",
            name="user",
        ),
        migrations.RemoveField(
            model_name="onboardtoken",
            name="user",
        ),
        migrations.DeleteModel(
            name="PayrollStats",
        ),
        migrations.AlterUniqueTogether(
            name="salaryrecord",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="salaryrecord",
            name="deliverer",
        ),
        migrations.DeleteModel(
            name="Deliverer",
        ),
        migrations.DeleteModel(
            name="OnboardToken",
        ),
        migrations.DeleteModel(
            name="SalaryRecord",
        ),
    ]
