# Generated by Django 5.1.1 on 2026-08-17 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_deliverydriver_remove_deliverer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ban_reason',
            field=models.CharField(blank=True, help_text='Ban berilgan sababi', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ban_until',
            field=models.DateTimeField(blank=True, help_text="Vaqtli ban bo'lsa, bu vaqtgacha ban davom etadi. Null bo'lsa, permanent ban.", null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='banned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_banned_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='banned_for',
            field=models.CharField(blank=True, help_text="Qaysi page uchun ban qo'yilgan (masalan: 'admin_login', 'dashboard', etc.)", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_permanent_ban',
            field=models.BooleanField(default=False, help_text="Permanent ban bo'lsa True. Faqat boshqa adminlar ochishi mumkin."),
        ),
    ]
