# Generated by Django 6.0.5 on 2026-09-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_customuser_ban_reason_customuser_ban_until_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin"), ("seller", "Seller"), ("driver", "Driver")],
                default="user",
                max_length=10,
            ),
        ),
    ]
