# Generated by Django 6.0.5 on 2026-09-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="credit_card",
            field=models.CharField(
                blank=True, help_text="O'chirilgan -Stripe Connect orqali saqlang", max_length=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="credit_card_expiry",
            field=models.CharField(
                blank=True, help_text="O'chirilgan -Stripe Connect orqali saqlang", max_length=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="credit_card_holder",
            field=models.CharField(
                blank=True, help_text="O'chirilgan -Stripe Connect orqali saqlang", max_length=255, null=True
            ),
        ),
    ]
