# Generated by Django 6.0.5 on 2026-08-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_alter_payment_order_alter_payment_stripe_charge_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Naqd pul"), ("card", "Karta (Stripe)"), ("online_stripe", "Onlayn to'lov (Stripe)")],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_charge_id",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
