# Generated by Django 5.1.1 on 2026-08-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_payment_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(choices=[("cash", "Naqd pul"), ("card", "Karta")], default="cash", max_length=20),
        ),
    ]
