    ### 1. Yangi foydalanuvchi uchun OTP kod so'rash
    # Bu so'rovni yuborganingizdan so'ng, terminalda chiqqan "session_id" ni va
    # emailga kelgan OTP kodni keyingi so'rov uchun eslab qoling.
    POST http://localhost:8000/api/v1/users/register/
    Content-Type: application/json

    {
      "email": "test@example.com",
      "full_name": "Test User"
    }

    ### 2. OTP kodni tekshirish (NOTO'G'RI KOD BILAN)
    # Bu so'rov 400 Bad Request xatoligini qaytarishi kerak.
    POST http://localhost:8000/api/v1/users/otp/verify/
    Content-Type: application/json

    {
      "session_id": "<oldingi_sorovdan_session_id_ni_qoying>",
      "code": "123456",
      "identifier": "test@example.com"
    }

    ### 3. OTP kodni tekshirish (TO'G'RI KOD BILAN)
    # Bu so'rov 200 OK statusini va tokenlarni qaytarishi kerak.
    POST http://localhost:8000/api/v1/users/otp/verify/
    Content-Type: application/json

    {
      "session_id": "<oldingi_sorovdan_session_id_ni_qoying>",
      "code": "<emailga_kelgan_togri_kodni_qoying>",
      "identifier": "test@example.com"
    }
