# Generated by Django 5.2.14 on 2026-05-17 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0003_remove_cartitem_cart_remove_cartitem_product_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotMenuStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_key",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("text_uz", models.TextField(verbose_name="Matn (UZ)")),
                (
                    "text_ru",
                    models.TextField(blank=True, null=True, verbose_name="Matn (RU)"),
                ),
                (
                    "text_en",
                    models.TextField(blank=True, null=True, verbose_name="Matn (EN)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BotInlineButton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(max_length=255, verbose_name="Tugma nomi (UZ)"),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Tugma nomi (RU)",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Tugma nomi (EN)",
                    ),
                ),
                ("callback_id", models.IntegerField()),
                ("row_number", models.PositiveIntegerField(default=1)),
                ("sort_order", models.PositiveIntegerField(default=1)),
                (
                    "menu_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buttons",
                        to="pharmacy.botmenustep",
                    ),
                ),
            ],
            options={
                "ordering": ["row_number", "sort_order"],
            },
        ),
    ]
