# Generated by Django 5.2.14 on 2026-05-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0005_rename_text_en_botmenustep_text_eng_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_ai_checked",
            field=models.BooleanField(default=False),
        ),
    ]
