# Generated by Django 5.1.1 on 2026-08-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0008_alter_category_options_category_is_default_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_us_text", models.TextField(verbose_name="Biz haqimizda matni")),
                (
                    "clients_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Mijozlar soni"
                    ),
                ),
                (
                    "experience_years",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tajriba yillari"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sayt Konfiguratsiyasi",
                "verbose_name_plural": "Sayt Konfiguratsiyasi",
            },
        ),
    ]
