# Generated by Django 5.1.1 on 2026-08-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0012_rename_pharmacy_cu_user_id_timestamp_idx_pharmacy_cu_user_id_12c7bc_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeruserhistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("view_product", "Mahsulot ko'rildi"),
                    ("view_seller", "Sotuvchi ko'rildi"),
                    ("add_to_cart", "Savatchaga qo'shildi"),
                    ("comment_create", "Fikr qoldirildi"),
                    ("comment_edit", "Fikr tahrirlandi"),
                    ("comment_delete", "Fikr o'chirildi"),
                    ("order_create", "Buyurtma qilindi"),
                    ("order_cancel", "Buyurtma bekor qilindi"),
                    ("admin_delete", "Admin tomonidan o'chirildi"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
