# Generated by Django 6.0.5 on 2026-08-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0013_alter_customeruserhistory_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_read", models.BooleanField(default=False)),
                ("replied", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="pharmacy_co_created_09f389_idx"),
                    models.Index(fields=["is_read"], name="pharmacy_co_is_read_254240_idx"),
                ],
            },
        ),
    ]
