# Generated by Django 5.1.1 on 2026-08-17 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BanRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip", models.CharField(blank=True, db_index=True, help_text="IP manzil", max_length=45, null=True)),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True, db_index=True, help_text="Device fingerprint", max_length=255, null=True
                    ),
                ),
                ("reason", models.TextField(help_text="Blok sababi")),
                (
                    "ban_type",
                    models.CharField(
                        choices=[("temporary", "Vaqtli"), ("permanent", "Doimiy")], default="temporary", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, db_index=True, help_text="Blok tugash vaqti (permanent uchun bo'sh)", null=True
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        choices=[("system", "Tizim"), ("admin", "Admin"), ("telegram", "Telegram")],
                        default="system",
                        help_text="Blok yaratuvchi",
                        max_length=50,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0, help_text="Xato so'rov soni")),
                ("source", models.CharField(blank=True, help_text="Manba (URL path, API endpoint)", max_length=100)),
                ("meta", models.JSONField(blank=True, default=dict, help_text="Qo'shimcha ma'lumotlar")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Foydalanuvchi (agar mavjud)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["ip", "is_active"], name="security_ba_ip_114863_idx"),
                    models.Index(fields=["fingerprint", "is_active"], name="security_ba_fingerp_620b67_idx"),
                    models.Index(fields=["expires_at", "is_active"], name="security_ba_expires_cc647d_idx"),
                ],
            },
        ),
    ]
