# Generated by Django 6.0.5 on 2026-08-20 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0002_banrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UndoLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("user", "Foydalanuvchi"),
                            ("medicine", "Dori"),
                            ("category", "Kategoriya"),
                            ("delivery", "Haydovchi"),
                            ("order", "Buyurtma"),
                            ("ban", "Ban"),
                        ],
                        max_length=20,
                    ),
                ),
                ("item_id", models.PositiveIntegerField()),
                ("item_name", models.CharField(max_length=255)),
                ("deleted_data", models.JSONField(default=dict)),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
                ("is_restored", models.BooleanField(default=False)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("restore_until", models.DateTimeField(db_index=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-deleted_at"],
                "indexes": [
                    models.Index(fields=["restore_until", "is_restored"], name="security_un_restore_bb1159_idx")
                ],
            },
        ),
    ]
