# Generated by Django 5.1.1 on 2026-08-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0003_undolog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="undolog",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("user", "Foydalanuvchi"),
                    ("medicine", "Dori"),
                    ("category", "Kategoriya"),
                    ("delivery", "Haydovchi"),
                    ("order", "Buyurtma"),
                    ("ban", "Ban"),
                    ("history", "Tarix"),
                ],
                max_length=20,
            ),
        ),
    ]
