# Generated by Django 5.1.1 on 2026-08-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0004_alter_undolog_item_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="target_id",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="target_type",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
