# Generated by Django 6.0.5 on 2026-08-26 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0005_auditlog_meta_auditlog_target_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActionHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("target_type", models.CharField(blank=True, max_length=64, null=True)),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["-timestamp"], name="security_au_timesta_cbae00_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["user", "-timestamp"], name="security_au_user_id_6d8368_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["target_type", "target_id"], name="security_au_target__ebaafd_idx"),
        ),
        migrations.AddField(
            model_name="useractionhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="action_history", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="useractionhistory",
            index=models.Index(fields=["-timestamp"], name="security_us_timesta_352e43_idx"),
        ),
        migrations.AddIndex(
            model_name="useractionhistory",
            index=models.Index(fields=["user", "-timestamp"], name="security_us_user_id_2ee679_idx"),
        ),
        migrations.AddIndex(
            model_name="useractionhistory",
            index=models.Index(fields=["action"], name="security_us_action_7464b6_idx"),
        ),
    ]
