# users/flags.py

# This file will be used by the frontend (via a simulated API endpoint or direct inclusion)
# to provide country data for the phone number input.

COUNTRY_DATA = [
    {
        "name": "Uzbekistan",
        "dial_code": "+998",
        "iso_code": "UZ",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Russia",
        "dial_code": "+7",
        "iso_code": "RU",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "United States",
        "dial_code": "+1",
        "iso_code": "US",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "United Kingdom",
        "dial_code": "+44",
        "iso_code": "GB",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Kazakhstan",
        "dial_code": "+7",
        "iso_code": "KZ",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Kyrgyzstan",
        "dial_code": "+996",
        "iso_code": "KG",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Tajikistan",
        "dial_code": "+992",
        "iso_code": "TJ",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Turkmenistan",
        "dial_code": "+993",
        "iso_code": "TM",
        "min_length": 8,
        "max_length": 8,
    },
    {
        "name": "Germany",
        "dial_code": "+49",
        "iso_code": "DE",
        "min_length": 10,
        "max_length": 11,
    },
    {
        "name": "France",
        "dial_code": "+33",
        "iso_code": "FR",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Canada",
        "dial_code": "+1",
        "iso_code": "CA",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Australia",
        "dial_code": "+61",
        "iso_code": "AU",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "China",
        "dial_code": "+86",
        "iso_code": "CN",
        "min_length": 11,
        "max_length": 11,
    },
    {
        "name": "India",
        "dial_code": "+91",
        "iso_code": "IN",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Brazil",
        "dial_code": "+55",
        "iso_code": "BR",
        "min_length": 11,
        "max_length": 11,
    },
    {
        "name": "Mexico",
        "dial_code": "+52",
        "iso_code": "MX",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Japan",
        "dial_code": "+81",
        "iso_code": "JP",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "South Korea",
        "dial_code": "+82",
        "iso_code": "KR",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Italy",
        "dial_code": "+39",
        "iso_code": "IT",
        "min_length": 9,
        "max_length": 10,
    },
    {
        "name": "Spain",
        "dial_code": "+34",
        "iso_code": "ES",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Argentina",
        "dial_code": "+54",
        "iso_code": "AR",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Egypt",
        "dial_code": "+20",
        "iso_code": "EG",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "South Africa",
        "dial_code": "+27",
        "iso_code": "ZA",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Nigeria",
        "dial_code": "+234",
        "iso_code": "NG",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Indonesia",
        "dial_code": "+62",
        "iso_code": "ID",
        "min_length": 10,
        "max_length": 12,
    },
    {
        "name": "Pakistan",
        "dial_code": "+92",
        "iso_code": "PK",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Bangladesh",
        "dial_code": "+880",
        "iso_code": "BD",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Philippines",
        "dial_code": "+63",
        "iso_code": "PH",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Vietnam",
        "dial_code": "+84",
        "iso_code": "VN",
        "min_length": 9,
        "max_length": 10,
    },
    {
        "name": "Turkey",
        "dial_code": "+90",
        "iso_code": "TR",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Saudi Arabia",
        "dial_code": "+966",
        "iso_code": "SA",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "United Arab Emirates",
        "dial_code": "+971",
        "iso_code": "AE",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Israel",
        "dial_code": "+972",
        "iso_code": "IL",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Greece",
        "dial_code": "+30",
        "iso_code": "GR",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Portugal",
        "dial_code": "+351",
        "iso_code": "PT",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Netherlands",
        "dial_code": "+31",
        "iso_code": "NL",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Belgium",
        "dial_code": "+32",
        "iso_code": "BE",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Sweden",
        "dial_code": "+46",
        "iso_code": "SE",
        "min_length": 7,
        "max_length": 13,
    },
    {
        "name": "Norway",
        "dial_code": "+47",
        "iso_code": "NO",
        "min_length": 8,
        "max_length": 8,
    },
    {
        "name": "Denmark",
        "dial_code": "+45",
        "iso_code": "DK",
        "min_length": 8,
        "max_length": 8,
    },
    {
        "name": "Finland",
        "dial_code": "+358",
        "iso_code": "FI",
        "min_length": 9,
        "max_length": 10,
    },
    {
        "name": "Austria",
        "dial_code": "+43",
        "iso_code": "AT",
        "min_length": 10,
        "max_length": 11,
    },
    {
        "name": "Switzerland",
        "dial_code": "+41",
        "iso_code": "CH",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Ireland",
        "dial_code": "+353",
        "iso_code": "IE",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "New Zealand",
        "dial_code": "+64",
        "iso_code": "NZ",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Singapore",
        "dial_code": "+65",
        "iso_code": "SG",
        "min_length": 8,
        "max_length": 8,
    },
    {
        "name": "Malaysia",
        "dial_code": "+60",
        "iso_code": "MY",
        "min_length": 7,
        "max_length": 10,
    },
    {
        "name": "Thailand",
        "dial_code": "+66",
        "iso_code": "TH",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Hong Kong",
        "dial_code": "+852",
        "iso_code": "HK",
        "min_length": 8,
        "max_length": 8,
    },
    {
        "name": "Taiwan",
        "dial_code": "+886",
        "iso_code": "TW",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "South Africa",
        "dial_code": "+27",
        "iso_code": "ZA",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Egypt",
        "dial_code": "+20",
        "iso_code": "EG",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Morocco",
        "dial_code": "+212",
        "iso_code": "MA",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Algeria",
        "dial_code": "+213",
        "iso_code": "DZ",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Tunisia",
        "dial_code": "+216",
        "iso_code": "TN",
        "min_length": 8,
        "max_length": 8,
    },
    {
        "name": "Kenya",
        "dial_code": "+254",
        "iso_code": "KE",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Ghana",
        "dial_code": "+233",
        "iso_code": "GH",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Colombia",
        "dial_code": "+57",
        "iso_code": "CO",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Peru",
        "dial_code": "+51",
        "iso_code": "PE",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Chile",
        "dial_code": "+56",
        "iso_code": "CL",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Venezuela",
        "dial_code": "+58",
        "iso_code": "VE",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Ecuador",
        "dial_code": "+593",
        "iso_code": "EC",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Bolivia",
        "dial_code": "+591",
        "iso_code": "BO",
        "min_length": 8,
        "max_length": 8,
    },
    {
        "name": "Paraguay",
        "dial_code": "+595",
        "iso_code": "PY",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Uruguay",
        "dial_code": "+598",
        "iso_code": "UY",
        "min_length": 8,
        "max_length": 8,
    },
    {
        "name": "Cuba",
        "dial_code": "+53",
        "iso_code": "CU",
        "min_length": 8,
        "max_length": 8,
    },
    {
        "name": "Dominican Republic",
        "dial_code": "+1",
        "iso_code": "DO",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Puerto Rico",
        "dial_code": "+1",
        "iso_code": "PR",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Jamaica",
        "dial_code": "+1",
        "iso_code": "JM",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Trinidad and Tobago",
        "dial_code": "+1",
        "iso_code": "TT",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Bahamas",
        "dial_code": "+1",
        "iso_code": "BS",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Barbados",
        "dial_code": "+1",
        "iso_code": "BB",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Guyana",
        "dial_code": "+592",
        "iso_code": "GY",
        "min_length": 7,
        "max_length": 7,
    },
    {
        "name": "Suriname",
        "dial_code": "+597",
        "iso_code": "SR",
        "min_length": 7,
        "max_length": 7,
    },
    {
        "name": "French Guiana",
        "dial_code": "+594",
        "iso_code": "GF",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Guadeloupe",
        "dial_code": "+590",
        "iso_code": "GP",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Martinique",
        "dial_code": "+596",
        "iso_code": "MQ",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Réunion",
        "dial_code": "+262",
        "iso_code": "RE",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Mayotte",
        "dial_code": "+262",
        "iso_code": "YT",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "New Caledonia",
        "dial_code": "+687",
        "iso_code": "NC",
        "min_length": 6,
        "max_length": 6,
    },
    {
        "name": "French Polynesia",
        "dial_code": "+689",
        "iso_code": "PF",
        "min_length": 6,
        "max_length": 6,
    },
    {
        "name": "Wallis and Futuna",
        "dial_code": "+681",
        "iso_code": "WF",
        "min_length": 6,
        "max_length": 6,
    },
    {
        "name": "Saint Pierre and Miquelon",
        "dial_code": "+508",
        "iso_code": "PM",
        "min_length": 6,
        "max_length": 6,
    },
    {
        "name": "Saint Barthélemy",
        "dial_code": "+590",
        "iso_code": "BL",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Saint Martin",
        "dial_code": "+590",
        "iso_code": "MF",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Greenland",
        "dial_code": "+299",
        "iso_code": "GL",
        "min_length": 6,
        "max_length": 6,
    },
    {
        "name": "Faroe Islands",
        "dial_code": "+298",
        "iso_code": "FO",
        "min_length": 6,
        "max_length": 6,
    },
    {
        "name": "Iceland",
        "dial_code": "+354",
        "iso_code": "IS",
        "min_length": 7,
        "max_length": 7,
    },
    {
        "name": "Malta",
        "dial_code": "+356",
        "iso_code": "MT",
        "min_length": 8,
        "max_length": 8,
    },
    {
        "name": "Cyprus",
        "dial_code": "+357",
        "iso_code": "CY",
        "min_length": 8,
        "max_length": 8,
    },
    {
        "name": "Luxembourg",
        "dial_code": "+352",
        "iso_code": "LU",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Monaco",
        "dial_code": "+377",
        "iso_code": "MC",
        "min_length": 8,
        "max_length": 9,
    },
    {
        "name": "Andorra",
        "dial_code": "+376",
        "iso_code": "AD",
        "min_length": 6,
        "max_length": 9,
    },
    {
        "name": "San Marino",
        "dial_code": "+378",
        "iso_code": "SM",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Vatican City",
        "dial_code": "+379",
        "iso_code": "VA",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Liechtenstein",
        "dial_code": "+423",
        "iso_code": "LI",
        "min_length": 7,
        "max_length": 9,
    },
    {
        "name": "Gibraltar",
        "dial_code": "+350",
        "iso_code": "GI",
        "min_length": 8,
        "max_length": 8,
    },
    {
        "name": "Guernsey",
        "dial_code": "+44",
        "iso_code": "GG",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Jersey",
        "dial_code": "+44",
        "iso_code": "JE",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Isle of Man",
        "dial_code": "+44",
        "iso_code": "IM",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Bermuda",
        "dial_code": "+1",
        "iso_code": "BM",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Cayman Islands",
        "dial_code": "+1",
        "iso_code": "KY",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Turks and Caicos Islands",
        "dial_code": "+1",
        "iso_code": "TC",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "British Virgin Islands",
        "dial_code": "+1",
        "iso_code": "VG",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "U.S. Virgin Islands",
        "dial_code": "+1",
        "iso_code": "VI",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Anguilla",
        "dial_code": "+1",
        "iso_code": "AI",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Antigua and Barbuda",
        "dial_code": "+1",
        "iso_code": "AG",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Dominica",
        "dial_code": "+1",
        "iso_code": "DM",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Grenada",
        "dial_code": "+1",
        "iso_code": "GD",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Montserrat",
        "dial_code": "+1",
        "iso_code": "MS",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Saint Kitts and Nevis",
        "dial_code": "+1",
        "iso_code": "KN",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Saint Lucia",
        "dial_code": "+1",
        "iso_code": "LC",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Saint Vincent and the Grenadines",
        "dial_code": "+1",
        "iso_code": "VC",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Sint Maarten",
        "dial_code": "+1",
        "iso_code": "SX",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Aruba",
        "dial_code": "+297",
        "iso_code": "AW",
        "min_length": 7,
        "max_length": 7,
    },
    {
        "name": "Curaçao",
        "dial_code": "+599",
        "iso_code": "CW",
        "min_length": 7,
        "max_length": 7,
    },
    {
        "name": "Bonaire",
        "dial_code": "+599",
        "iso_code": "BQ",
        "min_length": 7,
        "max_length": 7,
    },
    {
        "name": "Guam",
        "dial_code": "+1",
        "iso_code": "GU",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Northern Mariana Islands",
        "dial_code": "+1",
        "iso_code": "MP",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "American Samoa",
        "dial_code": "+1",
        "iso_code": "AS",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Palau",
        "dial_code": "+680",
        "iso_code": "PW",
        "min_length": 7,
        "max_length": 7,
    },
    {
        "name": "Micronesia",
        "dial_code": "+691",
        "iso_code": "FM",
        "min_length": 7,
        "max_length": 7,
    },
    {
        "name": "Marshall Islands",
        "dial_code": "+692",
        "iso_code": "MH",
        "min_length": 7,
        "max_length": 7,
    },
    {
        "name": "Nauru",
        "dial_code": "+674",
        "iso_code": "NR",
        "min_length": 7,
        "max_length": 7,
    },
    {
        "name": "Kiribati",
        "dial_code": "+686",
        "iso_code": "KI",
        "min_length": 5,
        "max_length": 5,
    },
    {
        "name": "Tuvalu",
        "dial_code": "+688",
        "iso_code": "TV",
        "min_length": 5,
        "max_length": 5,
    },
    {
        "name": "Solomon Islands",
        "dial_code": "+677",
        "iso_code": "SB",
        "min_length": 7,
        "max_length": 7,
    },
    {
        "name": "Vanuatu",
        "dial_code": "+678",
        "iso_code": "VU",
        "min_length": 7,
        "max_length": 7,
    },
    {
        "name": "Fiji",
        "dial_code": "+679",
        "iso_code": "FJ",
        "min_length": 7,
        "max_length": 7,
    },
    {
        "name": "Tonga",
        "dial_code": "+676",
        "iso_code": "TO",
        "min_length": 7,
        "max_length": 7,
    },
    {
        "name": "Samoa",
        "dial_code": "+685",
        "iso_code": "WS",
        "min_length": 7,
        "max_length": 7,
    },
    {
        "name": "Cook Islands",
        "dial_code": "+682",
        "iso_code": "CK",
        "min_length": 5,
        "max_length": 5,
    },
    {
        "name": "Niue",
        "dial_code": "+683",
        "iso_code": "NU",
        "min_length": 4,
        "max_length": 4,
    },
    {
        "name": "Tokelau",
        "dial_code": "+690",
        "iso_code": "TK",
        "min_length": 4,
        "max_length": 4,
    },
    {
        "name": "Pitcairn Islands",
        "dial_code": "+64",
        "iso_code": "PN",
        "min_length": 4,
        "max_length": 4,
    },
    {
        "name": "Christmas Island",
        "dial_code": "+61",
        "iso_code": "CX",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Cocos (Keeling) Islands",
        "dial_code": "+61",
        "iso_code": "CC",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Norfolk Island",
        "dial_code": "+672",
        "iso_code": "NF",
        "min_length": 6,
        "max_length": 6,
    },
    {
        "name": "Bouvet Island",
        "dial_code": "+47",
        "iso_code": "BV",
        "min_length": 8,
        "max_length": 8,
    },
    {
        "name": "Heard Island and McDonald Islands",
        "dial_code": "+672",
        "iso_code": "HM",
        "min_length": 6,
        "max_length": 6,
    },
    {
        "name": "South Georgia and the South Sandwich Islands",
        "dial_code": "+500",
        "iso_code": "GS",
        "min_length": 5,
        "max_length": 5,
    },
    {
        "name": "French Southern Territories",
        "dial_code": "+262",
        "iso_code": "TF",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "United States Minor Outlying Islands",
        "dial_code": "+1",
        "iso_code": "UM",
        "min_length": 10,
        "max_length": 10,
    },
    {
        "name": "Afghanistan",
        "dial_code": "+93",
        "iso_code": "AF",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Albania",
        "dial_code": "+355",
        "iso_code": "AL",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Armenia",
        "dial_code": "+374",
        "iso_code": "AM",
        "min_length": 8,
        "max_length": 8,
    },
    {
        "name": "Azerbaijan",
        "dial_code": "+994",
        "iso_code": "AZ",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Belarus",
        "dial_code": "+375",
        "iso_code": "BY",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Bosnia and Herzegovina",
        "dial_code": "+387",
        "iso_code": "BA",
        "min_length": 8,
        "max_length": 8,
    },
    {
        "name": "Bulgaria",
        "dial_code": "+359",
        "iso_code": "BG",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Croatia",
        "dial_code": "+385",
        "iso_code": "HR",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Czech Republic",
        "dial_code": "+420",
        "iso_code": "CZ",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Estonia",
        "dial_code": "+372",
        "iso_code": "EE",
        "min_length": 7,
        "max_length": 8,
    },
    {
        "name": "Georgia",
        "dial_code": "+995",
        "iso_code": "GE",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Hungary",
        "dial_code": "+36",
        "iso_code": "HU",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Latvia",
        "dial_code": "+371",
        "iso_code": "LV",
        "min_length": 8,
        "max_length": 8,
    },
    {
        "name": "Lithuania",
        "dial_code": "+370",
        "iso_code": "LT",
        "min_length": 8,
        "max_length": 8,
    },
    {
        "name": "Moldova",
        "dial_code": "+373",
        "iso_code": "MD",
        "min_length": 8,
        "max_length": 8,
    },
    {
        "name": "Montenegro",
        "dial_code": "+382",
        "iso_code": "ME",
        "min_length": 8,
        "max_length": 8,
    },
    {
        "name": "North Macedonia",
        "dial_code": "+389",
        "iso_code": "MK",
        "min_length": 8,
        "max_length": 8,
    },
    {
        "name": "Poland",
        "dial_code": "+48",
        "iso_code": "PL",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Romania",
        "dial_code": "+40",
        "iso_code": "RO",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Serbia",
        "dial_code": "+381",
        "iso_code": "RS",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Slovakia",
        "dial_code": "+421",
        "iso_code": "SK",
        "min_length": 9,
        "max_length": 9,
    },
    {
        "name": "Slovenia",
        "dial_code": "+386",
        "iso_code": "SI",
        "min_length": 8,
        "max_length": 8,
    },
    {
        "name": "Ukraine",
        "dial_code": "+380",
        "iso_code": "UA",
        "min_length": 9,
        "max_length": 9,
    },
    # Add more countries as needed
]
