# Generated by Django 4.2.14 on 2026-08-12 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_order_driver_alter_orderdelivery_driver"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderDelivery",
        ),
    ]
