# Generated by Django 4.2.14 on 2026-08-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_delete_orderdelivery"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="customer",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Assigned", "Assigned to Driver"),
                    ("Accepted", "Accepted by Driver"),
                    ("Picked Up", "Picked Up by Driver"),
                    ("On The Way", "On The Way for Delivery"),
                    ("Arrived", "Arrived at User Location"),
                    ("Delivered", "Delivered"),
                    ("Canceled", "Canceled"),
                    ("Returned", "Returned"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
