# Generated by Django 4.2.14 on 2026-08-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_rename_customer_order_user_alter_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("assigned", "Assigned"), ("completed", "Completed")],
                        default="assigned",
                        max_length=50,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="order",
            name="accepted_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="assigned_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="driver",
        ),
        migrations.RemoveField(
            model_name="order",
            name="driver_notes",
        ),
        migrations.RemoveField(
            model_name="order",
            name="on_the_way_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="picked_up_at",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Delivered", "Delivered"),
                    ("Canceled", "Canceled"),
                    ("Returned", "Returned"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
