# Generated by Django 4.2.14 on 2026-08-13 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_deliveryorder_remove_order_accepted_at_and_more"),
        ("users", "0024_deliverydriver_remove_deliverer_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryorder",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.deliverydriver",
            ),
        ),
        migrations.AddField(
            model_name="deliveryorder",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.order"
            ),
        ),
    ]
