# Generated by Django 5.1.1 on 2026-08-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_deliveryorder_driver_deliveryorder_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Ixtiyoriy telefon raqami. Yetkazib berish uchun ishlatiladi.",
                max_length=20,
                null=True,
            ),
        ),
    ]
