# Generated by Django 6.0.5 on 2026-08-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_order_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Naqd pul"), ("card", "Karta (Stripe)"), ("online_stripe", "Onlayn to'lov (Stripe)")],
                default="cash",
                help_text="To'lov usuli",
                max_length=20,
            ),
        ),
    ]
