# Generated by Django 5.1.1 on 2026-08-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Naqd pul"), ("card", "Karta")],
                default="cash",
                help_text="To'lov usuli",
                max_length=20,
            ),
        ),
    ]
