# Generated by Django 6.0.5 on 2026-09-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0011_alter_order_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryorder",
            name="driver",
        ),
        migrations.AddField(
            model_name="deliveryorder",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryorder",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="accepted_at",
            field=models.DateTimeField(blank=True, help_text="When driver accepted the order", null=True),
        ),
        migrations.AlterField(
            model_name="deliveryorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("accepted", "Accepted"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="assigned",
                max_length=50,
            ),
        ),
    ]
