# Generated by Django 6.0.5 on 2026-09-13 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0012_remove_deliveryorder_driver_and_more"),
        ("users", "0026_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                help_text="Driver who accepted this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_orders",
                to="users.deliverydriver",
            ),
        ),
    ]
